### ISSUE TITLE
Issues when have resources in CloudFormation format

### ISSUE THREAD

**Issue by lusatiro** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#19]
`ServerlessError: An error occurred: NewDashintegrationProvConcLambdaAlias - Provisioned Concurrency configuration failed to be applied. Reason: FUNCTION_ERROR_INIT_FAILURE.`

I'm declaring some resources, as SQS queues, but that error occurs but it isn't very clear.
Is that a possibility that some override is happing under the hood?

```yaml
resources:
  Resources:
    One:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: "xxx_${self:provider.stage}.fifo"
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - NewIntegrationQueueDLQ
              - Arn
          maxReceiveCount: 5
    OneDLQ:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: "xxx_${self:provider.stage}_dlq.fifo"
    Two:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: "xxx_${self:provider.stage}.fifo"
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - PeriodicallyIntegrationsCheckerQueueDLQ
              - Arn
          maxReceiveCount: 5
    TwoDLQ:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: "xxx_${self:provider.stage}_dlq.fifo"
```
