### ISSUE TITLE
Doesn't scale down

### ISSUE THREAD

**Issue by saiumesh-apty** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#22]
Hey There! Thanks for plugin. we have one Lambda written Go and it scales up based on following config but it doesn't scale down. There's no traffic since couple hours. 

```
functions:
  storage:
    handler: bin/storage
    lambdaInsights: true
    reservedConcurrency: 800
    provisionedConcurrency: 1
    concurrencyAutoscaling:
      enabled: true
      maximum: 100
      minimum: 0
      usage: 0.75
      scaleInCooldown: 60
      scaleOutCooldown: 10
      customMetric:
        statistic: maximum
    events:
      - httpApi:
          path: /storage
          method: post
```

![Screenshot 2021-05-25 at 4 47 45 PM](https://user-images.githubusercontent.com/35692863/119505551-b3866d00-bd8a-11eb-83e8-7c8423609adb.png)

![Screenshot 2021-05-25 at 4 55 29 PM](https://user-images.githubusercontent.com/35692863/119505694-d749b300-bd8a-11eb-85b3-1c91642bd7fd.png)
