### ISSUE TITLE
Function provisioned concurrency unable to reach minimum

### ISSUE THREAD

**Issue by L0key** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#37]
With the following configuration:
```
plugins:
  - serverless-provisioned-concurrency-autoscaling
 ...
custom:
  provisionedConcurrency:
    ci: false
    uat: false
    prod: true
...
 functions:
  my_func:
    handler: handlers/my-handler
    provisionedConcurrency: 1
    concurrencyAutoscaling: ${self:custom.provisionedConcurrency.${opt:stage}} 
 ```

I was expecting to see the Lambda function's provisioned concurrency go to 1 whenever activity went to zero. It turns out the actual minimum is 2. I did check that the CloudWatch alarm for down-scaling the provisioned concurrency is in alarm and is enabled:
```
ProvisionedConcurrencyUtilization < 0.675 for 15 datapoints within 15 minutes
```
