### ISSUE TITLE
Setting enable with condition does not work

### ISSUE THREAD

**Issue by mskec** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#55]
I'm trying to set enabled based on some environment variable.

I tried to configure it like this:
```yaml
concurrencyAutoscaling:
  enabled: [!Equals ["someEnv", "production"]]
```

This doesn't work and the plugin doesn't add the autoscaling config because it's strictly checking `instance.concurrencyAutoscaling.enabled === true`.

`console.log(instance.concurrencyAutoscaling.enabled) // outputs [ { 'Fn::Equals': [ 'someEnv', 'production' ] } ]`

Is it possible to enable autoscaling with a condition?

**Comment by claydanford** [comment]
Hi @mskec, you can probably accomplish this with parameters.

```yaml
params:
  default:
    concurrencyAutoscaling: false
  prod:
    concurrencyAutoscaling: true
  dev:
    concurrencyAutoscaling: false

...
concurrencyAutoscaling:
  enabled: ${params:concurrencyAutoscaling}

```
https://www.serverless.com/framework/docs/guides/parameters
