### ISSUE TITLE
Scaling down provisioned concurrency is not working

### ISSUE THREAD

**Issue by Kunalkatdare** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#59]
@claydanford / @flxgn  here's my config:
```
provisionedConcurrency: 1
config:
  enabled: true
  alias: provisioned
  usage: 0.80
  scheduledActions:
    - name: BusinessHours
      schedule: "cron(30 12 ? * 2-6 *)" # Start of business day (UTC)
      action:
        minimum: 1
```

when I see the lambda provisioned concurrency its is set to 2. Even during periods with no traffic. I've noticed that it doesn't scale down.
How can the minimum be set to 1 as per the config?

<img width="1064" alt="Screenshot 2024-06-25 at 1 02 18 PM" src="https://github.com/neiman-marcus/serverless-provisioned-concurrency-autoscaling/assets/15366226/0ad74c98-9c79-44e3-ba3d-361ae2256a34">
<img width="1125" alt="Screenshot 2024-06-25 at 1 03 12 PM" src="https://github.com/neiman-marcus/serverless-provisioned-concurrency-autoscaling/assets/15366226/e52f504f-4b55-4666-a7ce-244cd6a7fbd8">
